version: "3.8"
services:
    mongo:
        image: mongo:6.0.4
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        volumes:
            - "db:/data/db"
    api:
        build: ./api
        restart: always
        ports:
            - 8000:8000
    spa:
        build: ./spa
        restart: always
        ports:
            - 80:80
volumes:
    db:
        external: true